### PR TITLE
Updated generate_model_yaml macro to correctly handle nested bigquery…

### LINKED ISSUE #27: Generate_model_yaml doesn't recognize nested BigQuery columns
### Describe the bug
generate_model_yaml doesn't recognize nested bigquery columns

### Steps to reproduce
Create a model with nested columns, either through STRUCT() or ARRAY(), for example:
```
STRUCT(
   source,
   medium,
   source_medium
) analytics
```
### Expected results
The macro should print out the nested columns as well, now it prints out only the "main" column/field.
With the example above we should get
source, medium, source_medium and analytics as columns in the yaml output

### Actual results
The macro prints out only the "main" column/field which is analytics

### System information
**The contents of your `packages.yml` file:**
```
packages:
  - package: fishtown-analytics/dbt_utils
    version: 0.5.0
  - package: fishtown-analytics/codegen
    version: 0.1.0
```
**Which database are you using dbt with?**
- [x] bigquery

**The output of `dbt --version`:**
```
installed version: 0.17.1
   latest version: 0.17.1
```

**The operating system you're using:**
Ubuntu 18.04
**The output of `python --version`:**
Python 3.8.1

### Are you interested in contributing the fix?
I would love to, unfortunately my knowledge of Jinja isn't sufficient so I'd appreciate some pointers

### PR DESCRIPTION
**Pull request by bodschut**
This is a:
- [x] bug fix PR with no breaking changes — please ensure the base branch is `main`
- [ ] new functionality — please ensure the base branch is the latest `dev/` branch
- [ ] a breaking change — please ensure the base branch is the latest `dev/` branch

## Description & motivation
Fixes #27 

## Checklist
- [x] I have verified that these changes work locally
- [x] I have updated the README.md (if applicable)
- [ ] I have added tests & descriptions to my models (and macros if applicable)
- [ ] I have added an entry to CHANGELOG.md

### CODE REVIEW

**Comment by joellabes** [comment]
Hi @bodschut, thanks for opening this - as you noted in #27, we'll definitely want some integration tests to ensure everything's working correctly. 

Have a look at https://github.com/dbt-labs/dbt-codegen/tree/main/integration_tests/tests for some examples - you can create another source table following [this pattern](https://github.com/dbt-labs/dbt-codegen/blob/main/integration_tests/macros/operations/create_source_table.sql) - you'll need to only run it if the current adapter is BigQuery of course (see [`target.type`](https://docs.getdbt.com/reference/dbt-jinja-functions/target#common)

File: macros/generate_model_yaml.sql [hunk 1]
```diff
@@ -14,9 +32,7 @@
 {%- set columns = adapter.get_columns_in_relation(relation) -%}
 
 {% for column in columns %}
-    {% do model_yaml.append('      - name: ' ~ column.name | lower ) %}
-    {% do model_yaml.append('        description: "' ~ column_desc_dict.get(column.name | lower,'') ~ '"') %}
-    {% do model_yaml.append('') %}
+    {% set model_yaml = generate_column_yaml(column, model_yaml, column_desc_dict) %}
```
Comment (dbeatty10) [inline macros/generate_model_yaml.sql:35]: After merging with the latest code, the integration tests are yielding an error like:
```
Compilation Error in test test_generate_model_yaml (tests/test_generate_model_yaml.sql)
  'generate_column_yaml' is undefined
```

This should fix that:
```suggestion
    {% set model_yaml = codegen.generate_column_yaml(column, model_yaml, column_desc_dict) %}
```

**Review by dbeatty10 — APPROVED** [review]
@bodschut thanks for submitting this! 🏆 

I added some tests and everything looks good ✅

File: macros/generate_model_yaml.sql [hunk 2]
```diff
@@ -1,3 +1,22 @@
+{% macro generate_column_yaml(column, model_yaml, column_desc_dict, parent_column_name="") %}
+    {% if parent_column_name %}
+        {% set column_name = parent_column_name ~ "." ~ column.name %}
+    {% else %}
+        {% set column_name = column.name %}
+    {% endif %}
+
+    {% do model_yaml.append('      - name: ' ~ column.name | lower ) %}
```
Comment (Zatte) [inline macros/generate_model_yaml.sql:8]: Sorry for poking an old PR but shouldn't this line read(?):
```
{% do model_yaml.append('      - name: ' ~ column_name  | lower ) %}
```

Comment (dbeatty10) [reply macros/generate_model_yaml.sql:8]: I'm not sure one way or the other @Zatte

@bodschut Some questions:
1. What do you think of @Zatte 's question about `column_name` versus `column.name`?
1. Is there something more descriptive than `column_name` that would be accurate, like `aliased_parent_column_name`?
1. Is `parent_column_name` even used as a parameter? It's not explicitly set [here](https://github.com/dbt-labs/dbt-codegen/blob/6da8a04657e7d5765dcd3a329a55495cf75b2b98/macros/generate_model_yaml.sql#L41), and the `generate_column_yaml` looks like a "private" macro internal to `codegen` rather than a "public" macro intended to be used by consumers.

Comment (Zatte) [reply macros/generate_model_yaml.sql:8]: For context; I use [generate_model_yaml-source](https://github.com/dbt-labs/dbt-codegen#generate_model_yaml-source) (which calls this private macro) on a nested struct in BigQuery

With the current state i only get "tail columns" as the column names (not the full parent hierarchy, dot delimited). I would expect the column names to contain the full parent hierarchy. 

Example. 
SQL 
```sql
SELECT 
   struct(
      "a" as a, 
      "b" as b
   ) as substruct
```
Current output 
```yaml
models:
  - name: model_struct
    description: ""
    columns:
      - name: a
        description: ""

      - name: b
        description: ""
```


Expected output 

```yaml
models:
  - name: model_struct
    description: ""
    columns:
      - name: substruct.a
        description: ""

      - name: substruct.b
        description: ""

```

The current output will be ambiguous in the case of multiple sub-structs (nested columns) with the same name.

Comment (dbeatty10) [reply macros/generate_model_yaml.sql:8]: This info is perfect @Zatte !

I was able to reproduce and see that your suggested fix works.

Opened this issue and will follow-up with a PR:
https://github.com/dbt-labs/dbt-codegen/issues/98

I took a peek at the commit history on this -- looks like @bodschut had it correct the first time around, and I accidentally foobar'd it when resolving a merge conflict 😬
